### ISSUE TITLE
Needs update to biomass libraries

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-NECN-Succession#1]
To be compatible with the new harvest extensions and the land use extension, Century needs to be re-coded to be compatible with the biomass libraries. Lesley Bross did so on a branch; needs to implemented on the trunk.

**Comment by lbross** [comment]
How should the libraries be handled? The options in order of my preference:
1. NuGet
2. Add a lib folder and store copies of the libraries there that were used to build the project. Project points libraries in this directory
3. Point project at C:\Program Files\LANDIS-II\v6\bin\extensions directory for libraries (current scenario). I don't like this because there is no control over which library is in the extensions folder. Also developers have to compile and copy the library before the century project can be compiled.

**Comment by rmscheller** [comment]
My order of preference:
1. Add library folder.
2. Point to local.
3. NuGet.  I get NuGet but I don't like it as it involves more technology, more accounts, passwords, etc. Although a wonderful tool for the more advanced developers, it is a barrier to our goal of enabling **scientists** to quickly download, tweak, test.

**Comment by lbross** [comment]
Going with adding the lib folder. It looks like this task also requires updates to the leaf-biomass-cohort library. Can you break that out into its own repository and give me commit privileges?

**Comment by rmscheller** [comment]
Lesley,

My understanding - perhaps wrong - is that the leaf-biomass-cohort library will become essentially defunct after the change.  By having PnET, Biomass, and Century Succession all working with the same biomass-cohort library, we need not have duplicate biomass-harvest and biomass-insect disturbances.

**Comment by lbross** [comment]
That is not what I'm finding. There are still lots of references to the leaf-biomass-cohort library. I did not make any of these changes originally. Brian M. made them and I was tasked with integrating them into an installer for Jonathan's group. Right now, I'm just trying to migrate Brian's changes to the current century code. I recommend checking with Brian M. if you need more details. I may also have an old e-mail or two that I can forward.

**Comment by rmscheller** [comment]
You're correct, references to leaf-biomass-cohorts should remain.

**Comment by lbross** [comment]
Can you break leaf-biomass-cohorts out into its own repository and give me commit privileges?

Also, do other extensions use this library? If so, they will need to be tested with the updated leaf-biomass-cohorts

**Comment by rmscheller** [comment]
I'm afraid I can't from this computer - GitBash not working.  It would have to wait until mid-March when I return to PDX.  Assuming all goes well, no other extension should need the library.
