### ISSUE TITLE
Decimal values require 64 bit input maps 

### ISSUE THREAD

**Issue by akretchun** [LANDIS-II-Foundation/Extension-NECN-Succession#10]
In order to use decimals on input maps, they need to be 64-bit, which LANDIS-II currently does not support. So we either need to scale the maps so they are integers, or make necessary updates to allow for 64 bit input maps

**Comment by rmscheller** [comment]
We can't convert to 64-bit at this time, so let's multiply by 1000 - will that give sufficient accuracy - and then divide by 1000 during input.  Need to make this super clear in the users guide.
