### ISSUE TITLE
Typo in pathname in Outputs.cs

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-NECN-Succession#100]
There is a typo in L638 of the Outputs class:

Now:
using (IOutputRaster<IntPixel> outputRaster = PlugIn.ModelCore.CreateRaster<IntPixel>(**pathavailablewater**, PlugIn.ModelCore.Landscape.Dimensions))

Should be:
using (IOutputRaster<IntPixel> outputRaster = PlugIn.ModelCore.CreateRaster<IntPixel>(**pathDeadWood**, PlugIn.ModelCore.Landscape.Dimensions))

**Comment by flakesw** [comment]
Fixed https://github.com/LANDIS-II-Foundation/Extension-NECN-Succession/commit/7da88a6fe11074b6ca6e848c0bb4df7ac09f3ddf
