### ISSUE TITLE
Fire effects - SOM reduction

### ISSUE THREAD

**Issue by akretchun** [LANDIS-II-Foundation/Extension-NECN-Succession#41]
I am examining the new 'LitterDuff' maps, and they do not appear to be reduced at all when fire occurs. So it does not appear as though the SOM reductions in the fire effects table are having their intended functionality

**Comment by rmscheller** [comment]
My quick tests indicate that the relevant algorithm is being called, see attached.
[Landis-log.txt](https://github.com/LANDIS-II-Foundation/Extension-NECN-Hydro-Succession/files/1942618/Landis-log.txt)

**Comment by akretchun** [comment]
Thanks I’ll check when I am back. I had set the reductions to 1.0 and wasn’t seeing any decrease in Duff biomass after a Fire in the single cell analysis. Maybe it’s something else

**Comment by rmscheller** [comment]
I double-checked to make sure it's reading in the reduction factors correctly.  It is.
[Landis-log.txt](https://github.com/LANDIS-II-Foundation/Extension-NECN-Hydro-Succession/files/1942653/Landis-log.txt)

**Comment by rmscheller** [comment]
Corrected.
