### ISSUE TITLE
FireCEfflux conversion?

### ISSUE THREAD

**Issue by akretchun** [LANDIS-II-Foundation/Extension-NECN-Succession#43]
Is the fire C efflux data output in the log.csv converted in any way? I was looking at it to compare to our independent emissions work and the numbers seemed very low, <10 g/C/m-2. I look to see if there was a g to Mg conversion or something but couldn't find it.

**Comment by rmscheller** [comment]
Alec, I think that column is defunct, should probably be removed.  Or we can fix it and keep it.

**Comment by akretchun** [comment]
Oh OK. I'm not going to use it for anything, I was just curious about how it compared to our much more exhaustive fuels consumption/emissions production approach and couldn't figure out what was going on. I guess this explains it!
