### ISSUE TITLE
Doesn't like zeros

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-NECN-Succession#47]
I'm getting errors when I try to read in maps that have zeros.  It's looking for additional digits (0.0) but a zero should be sufficient.  I'm having this issue with several of the maps, particularly field capacity, wilting point and now the SOM1surfC pool.  I'm not sure why the maps have zeros in the active cells yet, but it shouldn't trigger an error if you have 0, but it's fine if it's 0.0.

![image](https://user-images.githubusercontent.com/7819936/50363650-68b0fd00-0521-11e9-89a3-07b8eedb71dc.png)

**Comment by rmscheller** [comment]
Our latest version of GDAL is what is creating these issues.  I think we should consider ditching GDAL for v8.  At this point, the added value of many formats is no longer worth the hassle, in my opinion.  But there's little can be done until we do so.
