### ISSUE TITLE
Error message says map value is not between values when it is.

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-NECN-Succession#53]
When I read in a map, this error is triggered and NECN stops, even though the statement is correct.  That value IS between 0.0 and 0.75. 

Soil field capacity value 1.39698391743437E-12 is not between 0.0 and 0.75.

**Comment by rmscheller** [comment]
Melissa,
Somehow this issue escaped me!  I checked the code and suspect the issue is that x-12 exceeds the precision of a double.

**Comment by rmscheller** [comment]
Unclear if this was resolved.
