### ISSUE TITLE
additional map outputs to allow for easy model restart with Output Biomass Community extension? 

### ISSUE THREAD

**Issue by cjm23** [LANDIS-II-Foundation/Extension-NECN-Succession#58]
Could NECN write these additional maps in order to allow for seamless pauses and restarts when using the Output Biomass Community extension?
SOM1Nsurface
SOM1Nsoil
SOM2N
SOM3N
SOM1Csoil
SOM2C
SOM3C
deadcoarseroots
The goal would be to allow these maps to be written at say Year 20, pause the model, and then directly use these maps as inputs to NECN for the next set of years.

**Comment by rmscheller** [comment]
This is now ready for testing, Installer = 6.4.1
Inputs at L291: https://github.com/LANDIS-II-Foundation/Extension-NECN-Succession/blob/master/src/utility/InputParameterParser.cs

**Comment by rmscheller** [comment]
Charles, has this been tested?
