### ISSUE TITLE
Example File for 6.4

### ISSUE THREAD

**Issue by ZacharyRobbins** [LANDIS-II-Foundation/Extension-NECN-Succession#59]
Can we have an example file for v 6.4 to understand the structure of the new input value for cohort_litter_reduction in order to update files?

**Comment by rmscheller** [comment]
Is this not working?  https://github.com/LANDIS-II-Foundation/Extension-NECN-Succession/tree/master/testing/Core7-NECN6.4

**Comment by ZacharyRobbins** [comment]
I didn't think to do that. Thank you. But, there is no file "NECN Succession"  file in that test, it references  NECN_LTB_landscape.txt in the scenario. Elsewhere?

**Comment by rmscheller** [comment]
Good catch, forgot that file.  So added.

**Comment by ZacharyRobbins** [comment]
Thanks
