### ISSUE TITLE
Annual water budget output maps are reporting SOMTC

### ISSUE THREAD

**Issue by akretchun** [LANDIS-II-Foundation/Extension-NECN-Succession#6]
In the no-ecoregion branch, the 'Annual water budget' maps are reporting SOMTC, as defined in Output.cs. Not sure if this is an intentional placeholder or not.

**Comment by rmscheller** [comment]
Alec, that was a bad cut-and-paste, not intentional.  Needs to be fixed.

**Comment by akretchun** [comment]
OK will do. Do we have a method for calculating what that value is supposed to be?

**Comment by rmscheller** [comment]
Annual ppt-aet.

**Comment by akretchun** [comment]
Oh, right. OK, I'll take care of it
