### ISSUE TITLE
PowerShell no longer works to update DLLs

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-NECN-Succession#61]
I've never had trouble using PowerShell, but suddenly it loads but won't run. See how the button is red, not green.

![image](https://user-images.githubusercontent.com/7819936/88986456-dee21d80-d287-11ea-941d-59cbdaaf31d0.png)

**Comment by rmscheller** [comment]
The button to look for is two to the left, a sideways triangle.  You can also use F5.  I just tested on my machine and had no problem.    Do you have permissions to the directory?

**Comment by mslucash** [comment]
Sorry I meant the button is gray, not green, as in it's not an option for me (see original image). I don't know about permissions- did you take away my permissions to NECN? I think anyone should be able to compile code from a public directory. You can work around it anyway; it's just an extra step.

**Comment by rmscheller** [comment]
No, I meant permissions on your local computer.  I don't believe there's anything inherently wrong with the script and Powershell is still a Windows supported program.  I searched various forum and there's much information:  Google 'windows powershell running scripts is disabled'

**Comment by mslucash** [comment]
Just my computer, I guess. I'll work around it, like I have been. Just close the issue.

**Comment by ZacharyRobbins** [comment]
I also ran into this. If you run it as an admin (rt-click on Powershell, open as administrator),it overrides it. Not sure why it started so recently.  Also running as admin might change the output to your C: drive, and you may have to move the .dlls over.  If this helps any future finders.
