### ISSUE TITLE
Link to download NECN is not for most current version

### ISSUE THREAD

**Issue by dirtyDeak** [LANDIS-II-Foundation/Extension-NECN-Succession#73]
The download link on the NECN succession webpage (https://landis-ii-foundation.github.io/Extension-NECN-Succession/) links to github page to download NECN version 6.7, not the most current version (6.8)

**Comment by rmscheller** [comment]
v6.8 is still undergoing user testing.  If you would like to contribute to the testing, it would be most appreciated!

Rob
