### ISSUE TITLE
Salvage logging not reducing dead carbon pools

### ISSUE THREAD

**Issue by tucker-furniss** [LANDIS-II-Foundation/Extension-NECN-Succession#74]
Hi,

I am using NECN v6.6, SCRAPPLE v.3.0, and Biomass Harvest v.4.1. I am trying to use a SalvageLogging prescription to remove 100% of all fire-killed biomass. In my NECN setup file, I have all HarvestReductionParameters set to 1.0. In the Biomass Harvest setup file, I have the SalvageLogging prescription set to harvest 100% of available stands in one management zone, and 0% in another mgmt zone (for contrast). The output Harvest Prescripts maps (image below, top map) show that the prescription is indeed being applied correctly. 

The issue is that when I look at maps of DeadWoodBiomass, Soil Organic Matter, and Surface Litter (all of these maps are produced by the NECN extension), areas where SalvageLogging was applied are indistinguishable from other areas that burned but SalvageLogging was not applied. The top map here shows where SalvageLogging was applied (applied at every 1-yr time step), and the bottom map shows the difference between DeadWoodBiomass without fire or salvage logging and DeadWoodBiomass with fire and SalvageLogging. Areas that burned show up as green (more DeadWood), grey areas indicate no difference, and areas that were SalvageLogged should be red (less DeadWood, because it was all removed). 

I'm not sure if the problem is within NECN or Biomass Harvest. 

Any help on either finding the bug, or diagnosing why I am having this issue would be much appreciated!

![image](https://user-images.githubusercontent.com/81191951/144141092-fc3231b2-ab68-4ad4-904e-24a4f5e41080.png)

**Comment by tucker-furniss** [comment]
Update - I seem to have partially diagnosed the problem. It appears that NECN is not applying any of the HarvestReductionParameters unless some amount of live cohort harvesting actually occurs. So when using the "PlantOnly" keyword in the Biomass Harvest setup file, as one would with SalvageLogging if no live cohorts are to be cut, NECN does not apply the HarvestReductionParameters to the various carbon pools. In other words, NECN is not treating a harvest prescription with the CohortsRemoved parameter set to "PlantOnly" as a harvest event to which the HarvestReductionParameters are applied.

A work around is to use the "SpeciesList" keyword for the CohortsRemoved parameter in the Biomass Harvest setup file, rather than PlantOnly. I set the removal to 1% (so the minimum amount of live biomass is removed). Now NECN is reducing the dead biomass pools as expected. 

I'll leave the issue open for now as it appears this is a bug, and perhaps this work-around will help someone else who is having problems with salvage logging and NECN!

Cheers,
Tucker

**Comment by rmscheller** [comment]
Tucker,
That is correct.  The post-harvest C actions only occur following some cohort modification, however small.  Otherwise there is no way for succession to know that something has occurred and that it should take action.  So, I wouldn't describe this as a bug exactly, it's designed into the Core itself.  Our intention was always that cohorts are the common currency among extensions.

I cannot imagine any workaround either, except the process you described.  Could add an issue to harvest requesting an update to the User Guide so that other people will see your solution?

Thanks!

Rob

**Comment by tucker-furniss** [comment]
Copy that, thanks for confirming Rob!
