### ISSUE TITLE
NECN v6.8 LAI crashing

### ISSUE THREAD

**Issue by alisondeak** [LANDIS-II-Foundation/Extension-NECN-Succession#75]
I recently moved over to the newest version of NECN (v6.8) because earlier versions weren't compatible with the climate library the most recent version of SCRPPLE (v3.2.1) uses. Since moving over, each of the species cohort's LAI and AGB has begun crashing and, and in single-cell simulations the GrowthLimitLAI for each species doesn't budge from 0. I've made multiple attempts at modifying each of the parameters influencing LAI without any change in GrowthLimitLAI or any effects on LAI itself.

[NECN_succession.txt](https://github.com/LANDIS-II-Foundation/Extension-NECN-Succession/files/7830576/NECN_succession.txt)
[NECN-calibrate-log.csv](https://github.com/LANDIS-II-Foundation/Extension-NECN-Succession/files/7830577/NECN-calibrate-log.csv)
[NECN-succession-log.csv](https://github.com/LANDIS-II-Foundation/Extension-NECN-Succession/files/7830578/NECN-succession-log.csv)
[NECN_functional_group_params.csv](https://github.com/LANDIS-II-Foundation/Extension-NECN-Succession/files/7830579/NECN_functional_group_params.csv)

**Comment by rmscheller** [comment]
Zachary,

Any thoughts?

**Comment by alisondeak** [comment]
Ah, Zachary just emailed me - I had only noticed the new minimum LAI parameter and hadn't realized there was the new GrowthLAI parameter which I hadn't added to my functional parameters table. I imagine this is likely the issue.

**Comment by ZacharyRobbins** [comment]
It would be good if that threw an error. It seems like it is defaulting to zero rather than the traditional 0.47

**Comment by alisondeak** [comment]
It doesn't seem to be the issue. GrowthLAI is still stuck at 0 );

**Comment by rmscheller** [comment]
Alison,
Removing the previous method of reading in species parameters is the only reasonable fix I have for the problem.  As always, having two options for IO 2x+ the programming required!  The new version of 6.8 therefore requires that you use a CSV file.  Give it a go and I'll update the documentation before the official release... soon, hopefully.

**Comment by mslucash** [comment]
This issue is solved and could be closed.

**Comment by rmscheller** [comment]
Thanks!
