### ISSUE TITLE
Global replace of 'ecoregion' to 'climate_region'

### ISSUE THREAD

**Issue by akretchun** [LANDIS-II-Foundation/Extension-NECN-Succession#8]
It seems like eventually we are going to need to replace the term 'ecoregion' within the code to 'climate_region' or something more intuitive for the new functionality

**Comment by rmscheller** [comment]
I agree, let's do it.

**Comment by mslucash** [comment]
@rmscheller  When should we release NECN_Hydro?  This would help @akretchun decide when he should work on this task.

**Comment by rmscheller** [comment]
A good question.  End of Q1 2018?  I'll take care of the coding.

**Comment by mslucash** [comment]
Yes, that's a pretty easy deadline.  I hope you will change the formatting of the input files too to reduce confusion, not just the code.  Like ecoregions.txt file should be LandisData ClimateRegions etc.

**Comment by rmscheller** [comment]
Also, ecoregions still required by the Core.
