### ISSUE TITLE
Why is 1000 added to the output maps of NEE?

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-NECN-Succession#86]
Just curious why 1000 is added to NEE here in this line?

Output.cs. Line 560 
pixel.MapCode.Value = (short)(SiteVars.AnnualNEE[site] + 1000);

**Comment by rmscheller** [comment]
1000 was added because the maps cannot accommodate negative values.  Did I forget to include that in the User Guide?

**Comment by mslucash** [comment]
Not that I saw.

Melissa

Melissa Lucash
Research Assistant Professor
Department of Geography
University of Oregon

http://melissalucash.com
________________________________

**Comment by rmscheller** [comment]
Updated.  Thanks for the catch!
