### ISSUE TITLE
Reaching limits in NECN

### ISSUE THREAD

**Issue by jameslamping** [LANDIS-II-Foundation/Extension-NECN-Succession#94]
I am hitting some of the hard coded limits in NECN and was hoping they could be set higher for my landscape.

The first one is the species biomass limit that is currently set at 100000. SE Alaska has some species that are well above that in the plot estimates and I was wondering if we could set that to 300000 (a bit higher than I need but probably avoids having to set it higher in the future). 

The second is with the limit of latitude in the NECN succession text file. It is currently limited to 50 degrees, but the middle of my landscape is at 54 degrees and the top of my landscape is around 60 degrees. Could we increase that to somewhere above boreal latitudes?

Thank you!
James Lamping

**Comment by rmscheller** [comment]
Updated to 6.10.1 to accommodate the new limits.
