### ISSUE TITLE
Increase limitations on soil layer inputs

### ISSUE THREAD

**Issue by jameslamping** [LANDIS-II-Foundation/Extension-NECN-Succession#95]
I was wondering if you could increase the soil carbon input limitations in NECN. I am reaching the maximum allowed from the extension and have to modify my maps to get the scenario to run. My maximum values in the soil layers for NECN are below:

SOM1surfC = 1550
SOM1surfN = 155
SOM1soilC = 3100
SOM1soilN = 310
SOM2c = 91450
SOM2n = 3658
SOM3c = 58900
SOM3n = 6950
deadwood = 20000

**Comment by rmscheller** [comment]
Current limits:  
SOM1surfC = 10,000
SOM1surfN = 500
SOM1soilC = 15000
SOM1soilN = 500
SOM2c = 25,000 **
SOM2n = 1000 **
SOM3c = 30,000**
SOM3n = 1000**
deadwood = 75,000

I will update **

**Comment by rmscheller** [comment]
James,
Please test: https://github.com/LANDIS-II-Foundation/Extension-NECN-Succession/blob/master/deploy/installer/LANDIS-II-V7%20NECN%20Succession%206.10.2-setup.exe

**Comment by jameslamping** [comment]
Everything worked great up to SOM3N. Looks like limit is set to 5000 and my max is 6950

**Comment by rmscheller** [comment]
James, please test: 
https://github.com/LANDIS-II-Foundation/Extension-NECN-Succession/blob/master/deploy/installer/LANDIS-II-V7%20NECN%20Succession%206.10.3-setup.exe
